// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NetType {
    #[prost(enumeration = "Net", tag = "1")]
    pub net: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NetMessage {
    #[prost(oneof = "net_message::Message", tags = "1, 2, 3, 4")]
    pub message: ::core::option::Option<net_message::Message>,
}
/// Nested message and enum types in `NetMessage`.
pub mod net_message {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Message {
        /// VLAN setup and teardown
        #[prost(message, tag = "1")]
        VlanSetup(super::VlanSetup),
        #[prost(message, tag = "2")]
        VlanTeardown(super::VlanTeardown),
        /// VXLAN setup and teardown
        #[prost(message, tag = "3")]
        VxlanSetup(super::VxlanSetup),
        #[prost(message, tag = "4")]
        VxlanTeardown(super::VxlanTeardown),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VlanSetup {
    #[prost(message, optional, tag = "1")]
    pub msg_id: ::core::option::Option<MsgId>,
    #[prost(uint32, tag = "2")]
    pub vlan_id: u32,
    #[prost(string, tag = "3")]
    pub local_veth: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub remote_veth: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub local_ip: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub remote_ip: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "7")]
    pub host_mapping: ::core::option::Option<HostMapping>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VlanTeardown {
    #[prost(uint32, tag = "1")]
    pub vlan_id: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VxlanSetup {
    #[prost(message, optional, tag = "1")]
    pub msg_id: ::core::option::Option<MsgId>,
    #[prost(uint32, tag = "2")]
    pub vxlan_id: u32,
    #[prost(string, tag = "3")]
    pub ns_name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub ns_net: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub br_name: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub br_net: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub local_ip: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub remote_ip: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "9")]
    pub host_mapping: ::core::option::Option<HostMapping>,
    #[prost(string, optional, tag = "10")]
    pub docker_container: ::core::option::Option<::prost::alloc::string::String>,
    /// Set only on the backend-entry edge of a backend-triggered chain.
    /// The receiving client installs DNAT(dnat_port -> overlay_ip) so the
    /// initiator's traffic on that local port is steered into the new VXLAN.
    #[prost(uint32, optional, tag = "11")]
    pub dnat_port: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VxlanTeardown {
    #[prost(uint32, tag = "1")]
    pub vxlan_id: u32,
    #[prost(string, tag = "2")]
    pub ns_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub br_name: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "4")]
    pub docker_container: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MsgId {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Services {
    #[prost(message, repeated, tag = "1")]
    pub services: ::prost::alloc::vec::Vec<Service>,
}
#[derive(serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Service {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub port: u32,
    #[prost(string, optional, tag = "3")]
    pub docker_container: ::core::option::Option<::prost::alloc::string::String>,
}
/// Response to ServicesList: per-declared-service, the set of trigger ports
/// the client should observe via eBPF. When traffic is observed on one of
/// these ports, the client fires BackendTrigger(service_name, port).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServicesListResponse {
    #[prost(message, repeated, tag = "1")]
    pub service_triggers: ::prost::alloc::vec::Vec<ServiceTrigger>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServiceTrigger {
    #[prost(string, tag = "1")]
    pub service_name: ::prost::alloc::string::String,
    #[prost(uint32, repeated, tag = "2")]
    pub ports: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HostMapping {
    #[prost(string, tag = "1")]
    pub ip: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProxyRequest {
    #[prost(string, tag = "1")]
    pub client_ip: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub service_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Upstream {
    #[prost(string, tag = "1")]
    pub ip: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub port: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BackendTriggerRequest {
    #[prost(string, tag = "1")]
    pub service_name: ::prost::alloc::string::String,
    /// The trigger port observed by the client. Picks one chain among the
    /// service's configured triggers (one chain per port).
    #[prost(uint32, tag = "2")]
    pub port: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Empty {}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Net {
    Vxlan = 0,
    Vlan = 1,
}
impl Net {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Vxlan => "VXLAN",
            Self::Vlan => "VLAN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VXLAN" => Some(Self::Vxlan),
            "VLAN" => Some(Self::Vlan),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod nullnet_grpc_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct NullnetGrpcClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl NullnetGrpcClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> NullnetGrpcClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> NullnetGrpcClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            NullnetGrpcClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Network type declaration
        pub async fn network_type(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::NetType>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nullnet_grpc.NullnetGrpc/NetworkType",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("nullnet_grpc.NullnetGrpc", "NetworkType"));
            self.inner.unary(req, path, codec).await
        }
        /// Services list — response carries the trigger ports the caller should
        /// observe locally for the services it just declared as hosting.
        pub async fn services_list(
            &mut self,
            request: impl tonic::IntoRequest<super::Services>,
        ) -> std::result::Result<
            tonic::Response<super::ServicesListResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nullnet_grpc.NullnetGrpc/ServicesList",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("nullnet_grpc.NullnetGrpc", "ServicesList"));
            self.inner.unary(req, path, codec).await
        }
        /// Control channel
        pub async fn control_channel(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::MsgId>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::NetMessage>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nullnet_grpc.NullnetGrpc/ControlChannel",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("nullnet_grpc.NullnetGrpc", "ControlChannel"));
            self.inner.streaming(req, path, codec).await
        }
        /// Proxy
        pub async fn proxy(
            &mut self,
            request: impl tonic::IntoRequest<super::ProxyRequest>,
        ) -> std::result::Result<tonic::Response<super::Upstream>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nullnet_grpc.NullnetGrpc/Proxy",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("nullnet_grpc.NullnetGrpc", "Proxy"));
            self.inner.unary(req, path, codec).await
        }
        /// Backend trigger — for service-to-service chains that do not involve the proxy.
        pub async fn backend_trigger(
            &mut self,
            request: impl tonic::IntoRequest<super::BackendTriggerRequest>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nullnet_grpc.NullnetGrpc/BackendTrigger",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("nullnet_grpc.NullnetGrpc", "BackendTrigger"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod nullnet_grpc_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with NullnetGrpcServer.
    #[async_trait]
    pub trait NullnetGrpc: std::marker::Send + std::marker::Sync + 'static {
        /// Network type declaration
        async fn network_type(
            &self,
            request: tonic::Request<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::NetType>, tonic::Status>;
        /// Services list — response carries the trigger ports the caller should
        /// observe locally for the services it just declared as hosting.
        async fn services_list(
            &self,
            request: tonic::Request<super::Services>,
        ) -> std::result::Result<
            tonic::Response<super::ServicesListResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the ControlChannel method.
        type ControlChannelStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::NetMessage, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Control channel
        async fn control_channel(
            &self,
            request: tonic::Request<tonic::Streaming<super::MsgId>>,
        ) -> std::result::Result<
            tonic::Response<Self::ControlChannelStream>,
            tonic::Status,
        >;
        /// Proxy
        async fn proxy(
            &self,
            request: tonic::Request<super::ProxyRequest>,
        ) -> std::result::Result<tonic::Response<super::Upstream>, tonic::Status>;
        /// Backend trigger — for service-to-service chains that do not involve the proxy.
        async fn backend_trigger(
            &self,
            request: tonic::Request<super::BackendTriggerRequest>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct NullnetGrpcServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> NullnetGrpcServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for NullnetGrpcServer<T>
    where
        T: NullnetGrpc,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/nullnet_grpc.NullnetGrpc/NetworkType" => {
                    #[allow(non_camel_case_types)]
                    struct NetworkTypeSvc<T: NullnetGrpc>(pub Arc<T>);
                    impl<T: NullnetGrpc> tonic::server::UnaryService<super::Empty>
                    for NetworkTypeSvc<T> {
                        type Response = super::NetType;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::Empty>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as NullnetGrpc>::network_type(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = NetworkTypeSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nullnet_grpc.NullnetGrpc/ServicesList" => {
                    #[allow(non_camel_case_types)]
                    struct ServicesListSvc<T: NullnetGrpc>(pub Arc<T>);
                    impl<T: NullnetGrpc> tonic::server::UnaryService<super::Services>
                    for ServicesListSvc<T> {
                        type Response = super::ServicesListResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::Services>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as NullnetGrpc>::services_list(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ServicesListSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nullnet_grpc.NullnetGrpc/ControlChannel" => {
                    #[allow(non_camel_case_types)]
                    struct ControlChannelSvc<T: NullnetGrpc>(pub Arc<T>);
                    impl<T: NullnetGrpc> tonic::server::StreamingService<super::MsgId>
                    for ControlChannelSvc<T> {
                        type Response = super::NetMessage;
                        type ResponseStream = T::ControlChannelStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<tonic::Streaming<super::MsgId>>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as NullnetGrpc>::control_channel(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ControlChannelSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nullnet_grpc.NullnetGrpc/Proxy" => {
                    #[allow(non_camel_case_types)]
                    struct ProxySvc<T: NullnetGrpc>(pub Arc<T>);
                    impl<T: NullnetGrpc> tonic::server::UnaryService<super::ProxyRequest>
                    for ProxySvc<T> {
                        type Response = super::Upstream;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ProxyRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as NullnetGrpc>::proxy(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ProxySvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nullnet_grpc.NullnetGrpc/BackendTrigger" => {
                    #[allow(non_camel_case_types)]
                    struct BackendTriggerSvc<T: NullnetGrpc>(pub Arc<T>);
                    impl<
                        T: NullnetGrpc,
                    > tonic::server::UnaryService<super::BackendTriggerRequest>
                    for BackendTriggerSvc<T> {
                        type Response = super::Empty;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BackendTriggerRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as NullnetGrpc>::backend_trigger(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = BackendTriggerSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for NullnetGrpcServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "nullnet_grpc.NullnetGrpc";
    impl<T> tonic::server::NamedService for NullnetGrpcServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
