[[services]]
name = "color.com"
timeout = 0
proxy_dependencies = ["fs.color.com"]
max_networks = 2

[[services.triggers]]
port = 5555
chain = ["ts.color.com"]

[[services]]
name = "fs.color.com"
timeout = 30
