name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  CARGO_TERM_COLOR: always

# Linters inspired from here: https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
jobs:

  rust:
    name: ${{ matrix.os }}-latest
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu
#          - os: macos
#          - os: windows

    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src, rustfmt, clippy
      - name: install bpf-linker
        run: cargo install bpf-linker --locked

      - name: fmt
        run: |
          cargo fmt --all -- --check
          cargo fmt --manifest-path ebpf/Cargo.toml --all -- --check
      - name: build
        run: cargo xtask build
      - name: clippy
        run: cargo xtask lint
      - name: test
        env:
          NULLNET_BIN_PATH: ${{ github.workspace }}/target/bpfel-unknown-none/debug/nullnet
        run: cargo test --verbose -- --nocapture
